config = {
    "algs_name": "ps_dqn",
    "action_dim": 20,
    "lr": 0.001,
    "gamma": 0.9,
    "tau": 0.005,
    "batch_size": 32,
    "buffer_size": 2000,
    "hidden_dim": 32,
    "hidden_dim2": 32,
    "epsilon_ini": 0.5,
    "epsilon_final": 0.01,
    "softupdate_freq": 30,
    "epsilon": 0.5,
    "use_global_state": True,
    "epsilon_first_phase": 1000,
    "epsilon_second_phase": 1000,
    "use_delta_reward": True,
}
